[[redirects]]
  from = '/api/*'
  to = 'http://api.travelpayouts.com/:splat'
  status = 200
  headers = { Access-Control-Allow-Origin = '*', Authorization = '407ff446faae19091d7227e3be1bd57a'}
[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200